name: score_board
description: A professional score board application with modular architecture.
publish_to: none
version: 1.1.10+20260724
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  wakelock_plus: ^1.1.4
  flutter_tts: ^3.8.5
  # Analytics
  fl_umeng: ^4.0.2 
  package_info_plus: ^8.0.2
  in_app_review: ^2.0.9
  flutter_svg: ^2.0.17
  
  # Local packages
  common_utils:
    path: ./common_utils
  common_ui:
    path: ./common_ui
  common_bridge:
    path: ./common_bridge
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/icons/games/
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/score_board.png
  min_sdk_android: 21
